version: "3.0"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
    

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

    environment:
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    
  db:
    image: mongo:latest
    container_name: restaurantservice
    ports: 
      - "27018:27018"
    
  restaurant-api:
    build: ./restaurant-partner-api-service
    container_name: restaurant-service-api
    ports:
      - "7070:7070"
    depends_on:
      - zookeeper
      - kafka
      - db
      
    links:
      - kafka
     
    
