spring:
  profiles:
    active: prod

server:
  port: 6060
  

---

spring:
  profiles: dev
  data:
    mongodb:
      database: deliveryAgentAppDB
      port: 27017
      host: localhost
  kafka:
    producer:
      group-id: order-service
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: delivery-consumers
      
---


spring:
  profiles: prod
  data:
    mongodb:
      database: deliveryAgentAppDB
      port: 27017
      host: orderService
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      group-id: order-service
      auto-offset-reset: earliest
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: delivery-consumers