apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: swiggy-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-pod
      app: swiggy-api
  template:
    metadata:
      name: mongo-pod
      labels:
        name: mongo-pod
        app: swiggy-api
    spec:
      container:
        - name: orderService
          image: mongo:latest
          ports:
            - containerPort: 27017
