apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    name: order-service
    app: swiggy-api
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    name: order-service-app-pod
    app: swiggy-api
