apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    name: kafka-pod
    app: swiggy-api
spec:
  container:
    - name: kafka
      image: wurstmeister/kafka
      ports:
        - containerPort: 9092
