apiVersion: v1
kind: Pod
metadat:
  name: mongo-pod
  labels:
    name: mongo-pod
    app: swiggy-api
spec:
  container:
    - name: orderService
      image: mongo:latest
      ports:
        - containerPort: 27017
