apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  labels:
    name: restaurant-service
    app: swiggy-api
spec:
  type: LoadBalancer
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    name: resturant-service-app-pod
    app: swiggy-api
