apiVersion: v1
kind: Pod
metadata:
  name: resturant-service-app-pod
  labels:
    name: resturant-service-app-pod
    app: swiggy-api
spec:
  container:
    - name: resturant-service-app
      image: swiggy_restaurant-api:latest
      ports:
        - containerPort: 7070
