apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    name: zookeeper-service
    app: swiggy-api
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    name: zookeeper-pod
    app: swiggy-api
